// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://durzjytdbetlrmmqdamg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cnpqeXRkYmV0bHJtbXFkYW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTIxMjEsImV4cCI6MjA2MDQyODEyMX0._IOhwSR1Ndm2bcsMiC6-MvyOfDmi7d8bOD_5mChS-Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);